# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_auto_20171001_0109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
