# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
    ]
